name: poc_ai_quiz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.5+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.3
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  chopper: ^7.0.6
  get_it: ^7.6.4
  flutter_spinkit: ^5.2.0
  isolates: ^3.0.3+8
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  in_app_purchase: ^3.1.13
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  flutter_hooks: ^0.21.3+1
  purchases_flutter: ^9.10.6
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  onnxruntime: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  chopper_generator: ^7.0.4
  json_serializable: ^6.7.1
  drift_dev: ^2.15.0
  mocktail: ^1.0.3
  pigeon: ^22.7.0
  fimber: ^0.7.0

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/model/all_minilm_l6_v2.onnx
    - assets/model/vocab.txt
    - assets/model/tokenizer.json

flutter_gen:
  enabled: true
  output: lib/gen
  localizations:
    enabled: true
    output: lib/gen/l10n

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"